version: '3.1'

services:

  tanque_cheio_db:
    image: postgres
    ports: [5432:5432]
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}